export default {
  NO_AUTH_TOKEN: 'No auth token present',
  NO_ABBREV_ATTR: 'No subject abbreviation attribute present',
  INVALID_TOKEN: 'Can\'t login to WIS with provided credentials',
  CANT_GET_COURSE_BY_ABREV: 'Error occured while fetching course info by abbreviation',
  NO_COURSE_ID: 'No course ID param provided',
  NO_ITEM_ID: 'No item id provided',
  NO_STUDENT_ID: 'No student id provided',
  CANT_GET_ITEM_VARIANTS: 'Can\'t get items variants',
  CANT_GET_ITEM_DATA: 'Can\'t fetch items data',
  CANT_GET_ITEMS_STUDENTS: 'Can\'t get items students',
  ACTIVE_ITEM_NOT_SET: 'Active item is not set',
  CANT_GET_STUDENT_BY_ISIC: 'Can\'t get student by ISIC',
  STUDENT_ALREADY_AWARDED: 'Student was already awarded',
  CANT_WRITE_POINTS: 'Can\'t write points to student',
  POINTS_PER_ITEM_NOT_SET: 'Points per current item are not set',
  NO_COURSE_ABBRV: 'No course abbreviation provided',
  NO_ACADEMIC_YEAR: 'Academic year not provided',
  NO_SEMESTER: 'Semester not provided',
  NO_STUDENT_LOGIN: 'Student login not provided',
  NO_POINTS: 'Points to write not provided',
  NO_TEACHER_LOGIN: 'Teacher login not provided',

 };
